version: '3'

services:
  api:
    image: jbrdy/tas-server
    environment:
      - PORT=${SERVER_PORT}
      - DB_CONNECTION_STRING=mysql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - WEB_APP_URL=${WEB_APP_URL}
      - MG_FROM_EMAIL=${MG_FROM_EMAIL}
      - MG_API_KEY=${MG_API_KEY}
      - MG_DOMAIN=${MG_DOMAIN}
      - PLIVO_AUTH_ID=${PLIVO_AUTH_ID}
      - PLIVO_AUTH_TOKEN=${PLIVO_AUTH_TOKEN}
      - PLIVO_SRC_NUM=${PLIVO_SRC_NUM}
      - DB_SETUP_DEFAULT_ALLOWED_APPTS_PER_HOUR=${DB_SETUP_DEFAULT_ALLOWED_APPTS_PER_HOUR}
      - DB_SETUP_MAX_TFU_PER_APPT=${DB_SETUP_MAX_TFU_PER_APPT}
      - DB_SETUP_ARRIVAL_WINDOW_LENGTH=${DB_SETUP_ARRIVAL_WINDOW_LENGTH}
      - DB_SETUP_APPTS_QUERY_MAX_COUNT=${DB_SETUP_APPTS_QUERY_MAX_COUNT}
      - ROOT_USER_PW=${ROOT_USER_PW}
    restart: always
    ports:
      - 4000:${SERVER_PORT}
    volumes:
      - tas-server-logs:/tas-server/logs
    depends_on:
      - db

  remind:
    build:
      context: ./tas-remind
      args:
        port: ${SERVER_PORT}
        secret: ${SECRET_KEY}
        hour: ${REMIND_HOUR_UTC}
    restart: always
    depends_on:
      - api

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306

  backup:
    image: deitch/mysql-backup
    restart: always
    user: "0" # fixing backup permissions issue
    environment:
      - DB_DUMP_TARGET=/db-backup
      - DB_SERVER=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAMES=${DB_NAME}
      - DB_DUMP_BEGIN=2300
    volumes:
      - db-backup:/db-backup
    depends_on:
      - db

volumes:
  tas-server-logs:
  db-backup:
